apiVersion: v1
kind: Pod
metadata:
  name: "${POD_NAME}"
spec:
  hostNetwork: true
  nodeName: "${NODE}"
  restartPolicy: Never
  containers:
    - name: sysctl-setter
      image: nicolaka/netshoot:v0.15
      command:
        - /bin/sh
        - -c
        - "${SYSCTL_COMMANDS}"
      securityContext:
        privileged: true
      resources: {}
